baseURL = 'https://control-space.netlify.app/'
languageCode = 'en-us'
title = 'Ctrl+Space - The Intellisense Every Programmer Needs'
theme = 'anatole'

[markup.goldmark.renderer]
unsafe= true

[markup.highlight]
  codeFences = true
  guessSyntax = false
  lineNoStart = 1  
  lineNos = true
  lineNumbersInTable = true
  tabWidth = 4
  noClasses = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"