baseURL = 'https://control-space.netlify.app/'
languageCode = 'en-us'
title = 'Ctrl+Space - The Intellisense Every Programmer Needs'
theme = 'anatole'

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

